# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tobias/deal.ii-candi/deal.II-v9.2.0/examples/MA/KirasFM--minimal-example

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tobias/deal.ii-candi/deal.II-v9.2.0/examples/MA/KirasFM--minimal-example

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tobias/deal.ii-candi/deal.II-v9.2.0/examples/MA/KirasFM--minimal-example/CMakeFiles /home/tobias/deal.ii-candi/deal.II-v9.2.0/examples/MA/KirasFM--minimal-example/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tobias/deal.ii-candi/deal.II-v9.2.0/examples/MA/KirasFM--minimal-example/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named info

# Build rule for target.
info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 info
.PHONY : info

# fast build rule for target.
info/fast:
	$(MAKE) -f CMakeFiles/info.dir/build.make CMakeFiles/info.dir/build
.PHONY : info/fast

#=============================================================================
# Target rules for targets named distclean

# Build rule for target.
distclean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 distclean
.PHONY : distclean

# fast build rule for target.
distclean/fast:
	$(MAKE) -f CMakeFiles/distclean.dir/build.make CMakeFiles/distclean.dir/build
.PHONY : distclean/fast

#=============================================================================
# Target rules for targets named runclean

# Build rule for target.
runclean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 runclean
.PHONY : runclean

# fast build rule for target.
runclean/fast:
	$(MAKE) -f CMakeFiles/runclean.dir/build.make CMakeFiles/runclean.dir/build
.PHONY : runclean/fast

#=============================================================================
# Target rules for targets named release

# Build rule for target.
release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 release
.PHONY : release

# fast build rule for target.
release/fast:
	$(MAKE) -f CMakeFiles/release.dir/build.make CMakeFiles/release.dir/build
.PHONY : release/fast

#=============================================================================
# Target rules for targets named debug

# Build rule for target.
debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 debug
.PHONY : debug

# fast build rule for target.
debug/fast:
	$(MAKE) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/build
.PHONY : debug/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

#=============================================================================
# Target rules for targets named strip_comments

# Build rule for target.
strip_comments: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 strip_comments
.PHONY : strip_comments

# fast build rule for target.
strip_comments/fast:
	$(MAKE) -f CMakeFiles/strip_comments.dir/build.make CMakeFiles/strip_comments.dir/build
.PHONY : strip_comments/fast

#=============================================================================
# Target rules for targets named KirasFM--minimal-example

# Build rule for target.
KirasFM--minimal-example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 KirasFM--minimal-example
.PHONY : KirasFM--minimal-example

# fast build rule for target.
KirasFM--minimal-example/fast:
	$(MAKE) -f CMakeFiles/KirasFM--minimal-example.dir/build.make CMakeFiles/KirasFM--minimal-example.dir/build
.PHONY : KirasFM--minimal-example/fast

main.o: main.cc.o

.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) -f CMakeFiles/KirasFM--minimal-example.dir/build.make CMakeFiles/KirasFM--minimal-example.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i

.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) -f CMakeFiles/KirasFM--minimal-example.dir/build.make CMakeFiles/KirasFM--minimal-example.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s

.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) -f CMakeFiles/KirasFM--minimal-example.dir/build.make CMakeFiles/KirasFM--minimal-example.dir/main.cc.s
.PHONY : main.cc.s

source/boundary_values.o: source/boundary_values.cc.o

.PHONY : source/boundary_values.o

# target to build an object file
source/boundary_values.cc.o:
	$(MAKE) -f CMakeFiles/KirasFM--minimal-example.dir/build.make CMakeFiles/KirasFM--minimal-example.dir/source/boundary_values.cc.o
.PHONY : source/boundary_values.cc.o

source/boundary_values.i: source/boundary_values.cc.i

.PHONY : source/boundary_values.i

# target to preprocess a source file
source/boundary_values.cc.i:
	$(MAKE) -f CMakeFiles/KirasFM--minimal-example.dir/build.make CMakeFiles/KirasFM--minimal-example.dir/source/boundary_values.cc.i
.PHONY : source/boundary_values.cc.i

source/boundary_values.s: source/boundary_values.cc.s

.PHONY : source/boundary_values.s

# target to generate assembly for a file
source/boundary_values.cc.s:
	$(MAKE) -f CMakeFiles/KirasFM--minimal-example.dir/build.make CMakeFiles/KirasFM--minimal-example.dir/source/boundary_values.cc.s
.PHONY : source/boundary_values.cc.s

source/grid_generator.o: source/grid_generator.cc.o

.PHONY : source/grid_generator.o

# target to build an object file
source/grid_generator.cc.o:
	$(MAKE) -f CMakeFiles/KirasFM--minimal-example.dir/build.make CMakeFiles/KirasFM--minimal-example.dir/source/grid_generator.cc.o
.PHONY : source/grid_generator.cc.o

source/grid_generator.i: source/grid_generator.cc.i

.PHONY : source/grid_generator.i

# target to preprocess a source file
source/grid_generator.cc.i:
	$(MAKE) -f CMakeFiles/KirasFM--minimal-example.dir/build.make CMakeFiles/KirasFM--minimal-example.dir/source/grid_generator.cc.i
.PHONY : source/grid_generator.cc.i

source/grid_generator.s: source/grid_generator.cc.s

.PHONY : source/grid_generator.s

# target to generate assembly for a file
source/grid_generator.cc.s:
	$(MAKE) -f CMakeFiles/KirasFM--minimal-example.dir/build.make CMakeFiles/KirasFM--minimal-example.dir/source/grid_generator.cc.s
.PHONY : source/grid_generator.cc.s

source/maxwell_solver.o: source/maxwell_solver.cc.o

.PHONY : source/maxwell_solver.o

# target to build an object file
source/maxwell_solver.cc.o:
	$(MAKE) -f CMakeFiles/KirasFM--minimal-example.dir/build.make CMakeFiles/KirasFM--minimal-example.dir/source/maxwell_solver.cc.o
.PHONY : source/maxwell_solver.cc.o

source/maxwell_solver.i: source/maxwell_solver.cc.i

.PHONY : source/maxwell_solver.i

# target to preprocess a source file
source/maxwell_solver.cc.i:
	$(MAKE) -f CMakeFiles/KirasFM--minimal-example.dir/build.make CMakeFiles/KirasFM--minimal-example.dir/source/maxwell_solver.cc.i
.PHONY : source/maxwell_solver.cc.i

source/maxwell_solver.s: source/maxwell_solver.cc.s

.PHONY : source/maxwell_solver.s

# target to generate assembly for a file
source/maxwell_solver.cc.s:
	$(MAKE) -f CMakeFiles/KirasFM--minimal-example.dir/build.make CMakeFiles/KirasFM--minimal-example.dir/source/maxwell_solver.cc.s
.PHONY : source/maxwell_solver.cc.s

source/parameter_reader.o: source/parameter_reader.cc.o

.PHONY : source/parameter_reader.o

# target to build an object file
source/parameter_reader.cc.o:
	$(MAKE) -f CMakeFiles/KirasFM--minimal-example.dir/build.make CMakeFiles/KirasFM--minimal-example.dir/source/parameter_reader.cc.o
.PHONY : source/parameter_reader.cc.o

source/parameter_reader.i: source/parameter_reader.cc.i

.PHONY : source/parameter_reader.i

# target to preprocess a source file
source/parameter_reader.cc.i:
	$(MAKE) -f CMakeFiles/KirasFM--minimal-example.dir/build.make CMakeFiles/KirasFM--minimal-example.dir/source/parameter_reader.cc.i
.PHONY : source/parameter_reader.cc.i

source/parameter_reader.s: source/parameter_reader.cc.s

.PHONY : source/parameter_reader.s

# target to generate assembly for a file
source/parameter_reader.cc.s:
	$(MAKE) -f CMakeFiles/KirasFM--minimal-example.dir/build.make CMakeFiles/KirasFM--minimal-example.dir/source/parameter_reader.cc.s
.PHONY : source/parameter_reader.cc.s

source/surface_communicator.o: source/surface_communicator.cc.o

.PHONY : source/surface_communicator.o

# target to build an object file
source/surface_communicator.cc.o:
	$(MAKE) -f CMakeFiles/KirasFM--minimal-example.dir/build.make CMakeFiles/KirasFM--minimal-example.dir/source/surface_communicator.cc.o
.PHONY : source/surface_communicator.cc.o

source/surface_communicator.i: source/surface_communicator.cc.i

.PHONY : source/surface_communicator.i

# target to preprocess a source file
source/surface_communicator.cc.i:
	$(MAKE) -f CMakeFiles/KirasFM--minimal-example.dir/build.make CMakeFiles/KirasFM--minimal-example.dir/source/surface_communicator.cc.i
.PHONY : source/surface_communicator.cc.i

source/surface_communicator.s: source/surface_communicator.cc.s

.PHONY : source/surface_communicator.s

# target to generate assembly for a file
source/surface_communicator.cc.s:
	$(MAKE) -f CMakeFiles/KirasFM--minimal-example.dir/build.make CMakeFiles/KirasFM--minimal-example.dir/source/surface_communicator.cc.s
.PHONY : source/surface_communicator.cc.s

source/write_data_table.o: source/write_data_table.cc.o

.PHONY : source/write_data_table.o

# target to build an object file
source/write_data_table.cc.o:
	$(MAKE) -f CMakeFiles/KirasFM--minimal-example.dir/build.make CMakeFiles/KirasFM--minimal-example.dir/source/write_data_table.cc.o
.PHONY : source/write_data_table.cc.o

source/write_data_table.i: source/write_data_table.cc.i

.PHONY : source/write_data_table.i

# target to preprocess a source file
source/write_data_table.cc.i:
	$(MAKE) -f CMakeFiles/KirasFM--minimal-example.dir/build.make CMakeFiles/KirasFM--minimal-example.dir/source/write_data_table.cc.i
.PHONY : source/write_data_table.cc.i

source/write_data_table.s: source/write_data_table.cc.s

.PHONY : source/write_data_table.s

# target to generate assembly for a file
source/write_data_table.cc.s:
	$(MAKE) -f CMakeFiles/KirasFM--minimal-example.dir/build.make CMakeFiles/KirasFM--minimal-example.dir/source/write_data_table.cc.s
.PHONY : source/write_data_table.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... info"
	@echo "... distclean"
	@echo "... runclean"
	@echo "... release"
	@echo "... debug"
	@echo "... run"
	@echo "... edit_cache"
	@echo "... strip_comments"
	@echo "... KirasFM--minimal-example"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... source/boundary_values.o"
	@echo "... source/boundary_values.i"
	@echo "... source/boundary_values.s"
	@echo "... source/grid_generator.o"
	@echo "... source/grid_generator.i"
	@echo "... source/grid_generator.s"
	@echo "... source/maxwell_solver.o"
	@echo "... source/maxwell_solver.i"
	@echo "... source/maxwell_solver.s"
	@echo "... source/parameter_reader.o"
	@echo "... source/parameter_reader.i"
	@echo "... source/parameter_reader.s"
	@echo "... source/surface_communicator.o"
	@echo "... source/surface_communicator.i"
	@echo "... source/surface_communicator.s"
	@echo "... source/write_data_table.o"
	@echo "... source/write_data_table.i"
	@echo "... source/write_data_table.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

